apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitness-sa
  namespace: gitness

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: gitness
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods", "pods/exec", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitness-sa-deployment-binder
  namespace: gitness
subjects:
- kind: ServiceAccount
  name: gitness-sa
  namespace: gitness
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: gitness-sa-token
  namespace: gitness
  annotations:
    kubernetes.io/service-account.name: gitness-sa
type: kubernetes.io/service-account-token
